- gather_facts: true
  hosts: all
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: minikube
      tags: minikube
    - role: test-deployment
      tags: test-deployment
    - role: wireguard
      tags: wireguard
